# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4c058603-0d6b-4fc7-bae8-2054bfaa776a'
  imageRepository: 'rohitabrahamcontainercicd'
  containerRegistry: 'vlcregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MSDN Platforms Subscription(3)(cb697725-96ec-4e23-b0f1-9a862b9b3a6e)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container create -g $(resourceGrop) --name rohitabrahamcontainercicd --image $(acrLoginServer)/rohitabrahamcontainercicd:$(Build.BuildId) --cpu 1 --memory 1 --registry-login-server $(acrLoginServer) --registry-username $(acrName) --registry-password $(acrPassword) --dns-name-label rohitabrahamcontainercicd --ports 80'