apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetes-a1bc"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetes-a1bc"
  template:
    metadata:
      labels:
        app: "kubernetes-a1bc"
    spec:
      containers:
        - name: "kubernetes-a1bc"
          image: "myserviceregistryvlc.azurecr.io/kubernetes"
          ports:
          - containerPort: 80