apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetes-82dc"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetes-82dc"
  template:
    metadata:
      labels:
        app: "kubernetes-82dc"
    spec:
      containers:
        - name: "kubernetes-82dc"
          image: "myserviceregistryvlc.azurecr.io/kubernetes"
          ports:
          - containerPort: 80