apiVersion: v1
kind: Service
metadata:
    name: "kubernetes-82dc"
    labels:
        app: "kubernetes-82dc"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernetes-82dc"