# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - containers-app-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b775fa78f0474296aedbc8292906f0e4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_da6a3c54d6024f4491c7b1a0c00a0341 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b775fa78f0474296aedbc8292906f0e4 }}/rohitabraham02/express-application:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'containers-app-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e6a3a9c59622429f9b3612603c146fa7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b775fa78f0474296aedbc8292906f0e4 }}/rohitabraham02/express-application:${{ github.sha }}'